config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  resources :websites do
    collection do
      post :confirm
    end
  end
  resources :sessions, only: [:new, :create, :destroy]

  resources :users, only: [:new, :create, :show,] 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_validation { email.downcase! }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  has_many :websites
end

app/models/website.rb
class Website < ApplicationRecord
  validates :content, presence: true
  mount_uploader :image, ImageUploader

  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash.now[:danger] = "ログインに失敗しました"
      render "new"
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = "ログアウトしました"
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user.id)
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
  end


  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/controllers/websites_controller.rb
class WebsitesController < ApplicationController
  before_action :set_website, only: [:show, :edit, :update, :destroy]
  before_action :block_not_login_user, only: [:new]
  def index
    @websites = Website.all
  end

  def new
    @website = Website.new
  end

  def create
    @website = current_user.websites.build(website_params)
    if params[:back]
      render :new
    else
      if @website.save
        redirect_to new_website_path, notice: "投稿完了しました"
      else
        render :new
      end
    end
  end

  def show
  end

  def edit
  end

  def confirm
    @website = current_user.websites.build(website_params)
    render :new if @website.invalid?
  end

  def update
    if @website.update(website_params)
      redirect_to website_path, notice: "編集完了"
    else
      render :edit
    end
  end

  def destroy
    @website.destroy
    redirect_to websites_path, notice:"投稿を削除しました"
  end

  private

  def website_params
    params.require(:website).permit(:content, :image, :image_cache)
  end

  def set_website
    @website = Website.find(params[:id])
  end

  def block_not_login_user
    if logged_in? == false
      redirect_to new_user_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/websites_helper.rb
module WebsitesHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm' || action_name == 'create'
      confirm_websites_path
    elsif action_name == 'edit'
      website_path
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsExam2</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width">
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid > row">
    <header>
    <div class="top_menu">
    <%= link_to image_tag('top.png', class:'top_image'),websites_path %>
    <% if logged_in? %>
      <%= link_to @current_user.name ,user_path(current_user.id) %>
      <%= link_to "Logout",session_path(current_user.id),method: :delete %>
    <% else %>
      <%= link_to "Sign up",new_user_path %>
      <%= link_to "Login",new_session_path %>
    <% end %>
    </div>
    </header>
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>
    <div class="wrapper clerfix">
    <%= yield %>
    </div>
  </div>
  </body>
</html>

app/views/users/new.html.erb
<h1>Sign up</h1>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this @user from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: @user, local: true) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>

  <%= f.submit "Create my account" %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %>のページ</h1>

<p>メールアドレス: <%= @user.email %></p>
<%= link_to "一覧に戻る", websites_path %>

app/views/websites/_form.html.erb
<%= form_with(model: @website, local: true , url: choose_new_or_edit ) do |form| %>
  <% if @website.errors.any? %>
      <div id="error_explanation">
        <h2><%= @website.errors.count %>件のエラーがあります。</h2>
        <ul>
        <% @website.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <div class="Website_content">
      <%= form.text_area :content,size: "40x5",class: "text_area-control"%>
    </div>
    <div class="Website_image">
      <%= image_tag(@website.image.url) if @website.image && @website.image.url %>
      <%= form.file_field :image %>
      <%= form.hidden_field :image_cache %>
    </div>
    <%= form.submit %>
  <% end %>

<%= link_to '一覧に戻る', websites_path %>

app/views/websites/confirm.html.erb
<h3>以下の内容で、送信する。</h3>

<%= form_with(model: @website, local: true) do |form| %>
  <%= form.hidden_field :content %>
  <p>本文:<%= @website.content %></p>
  <%= image_tag(@website.image.url) if @website.image && @website.image.url %>
  <%= form.hidden_field :image_cache %>
  <%= form.submit  "登録する" %>
  <%= form.submit "戻る", name: 'back' %>
<% end %>

app/views/websites/edit.html.erb
<h2>投稿を編集</h2>

<%= render 'form' %>

app/views/websites/index.html.erb
<p><%= notice %></p>
<% if logged_in? %>
<p><%= link_to '新しく投稿する', new_website_path %></p>
<% else %>
<h2>Wellcome to Facebook</h2>
<h4>ログインしてください</h4>
<% end %>

<% @websites.each do |website| %>
<div class="user_timeline">
  <div class="user_name">
    <%= website.user.name %>
  </div>
  <div class="user_content">
    <%= website.content %>
  </div>
  <div class="user_image">
    <%= image_tag(website.image.url) if website.image && website.image.url %>
  </div>
  <div class="user_option">
    <%= link_to image_tag('show.png', class:'show_image'),website_path(website.id) %>
    <%= link_to image_tag('edit.png', class: 'edit_image'), edit_website_path(website.id) %>
    <%= link_to image_tag('trash.png', class: 'trash_image'), website_path(website.id), method: :delete ,data:{ confirm: '本当に削除してもよろしいですか？'} %>
  </div>
  </div>
<% end %>

app/views/websites/new.html.erb
<h2>投稿を作成</h2>

<%= render 'form' %>

app/views/websites/show.html.erb
<h2>投稿の詳細</h2>
<p><%= @website.content %></p>
<p>
  <%= image_tag @website.image.url %>
</p>
<%= link_to '一覧に戻る', websites_path %>